/*
 * Copyright (c) 2026 Timotej Adamec
 * SPDX-License-Identifier: MIT
 *
 * This file is part of the thesis:
 * "Multiplatform snagging system with code sharing maximisation"
 *
 * Czech Technical University in Prague
 * Faculty of Information Technology
 * Department of Software Engineering
 */

rootProject.name = "Snag"
enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")

pluginManagement {
    repositories {
        google {
            mavenContent {
                includeGroupAndSubgroups("androidx")
                includeGroupAndSubgroups("com.android")
                includeGroupAndSubgroups("com.google")
            }
        }
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositories {
        google {
            mavenContent {
                includeGroupAndSubgroups("androidx")
                includeGroupAndSubgroups("com.android")
                includeGroupAndSubgroups("com.google")
            }
        }
        mavenCentral()
    }
}

plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

includeBuild("build-logic")
include(":androidApp")
include(":composeApp")
include(":koinModulesAggregate:fe")
include(":koinModulesAggregate:be")
include(":testInfra:common")
include(":testInfra:fe")
include(":testInfra:be")
include(":server")
include(":feat:projects:business:model")
include(":feat:projects:business:rules")
include(":feat:projects:app:model")
include(":feat:projects:fe:app:api")
include(":feat:projects:fe:app:impl")
include(":feat:projects:fe:ports")
include(":feat:projects:fe:driven:impl")
include(":feat:projects:contract")
include(":feat:projects:be:driving:impl")
include(":feat:projects:be:driven:impl")
include(":feat:projects:be:driven:test")
include(":feat:projects:be:app:api")
include(":feat:projects:be:app:impl")
include(":feat:projects:be:ports")
include(":feat:projects:be:app:model")
include(":feat:projects:fe:driving:api")
include(":feat:projects:fe:driving:impl")
include(":feat:shared:database:fe:api")
include(":feat:shared:database:fe:impl")
include(":feat:shared:database:fe:test")
include(":feat:shared:database:be:impl")
include(":feat:shared:database:be:test")
include(":core:business:rules:api")
include(":core:business:rules:impl")
include(":lib:design:fe")
include(":lib:routing:fe")
include(":lib:routing:be")
include(":lib:routing:common")
include(":lib:configuration:common:api")
include(":lib:configuration:fe:api")
include(":lib:configuration:be:api")
include(":lib:network:common:impl")
include(":lib:network:be:api")
include(":lib:network:be:impl")
include(":core:network:fe")
include(":core:storage:fe")
include(":lib:network:fe:api")
include(":lib:network:fe:impl")
include(":lib:network:fe:test")
include(":feat:structures:contract")
include(":feat:structures:be:driving:impl")
include(":lib:network:be:test")
include(":feat:projects:fe:driven:test")
include(":core:foundation:be")
include(":core:foundation:fe")
include(":core:foundation:common")
include(":feat:findings:business:model")
include(":feat:findings:app:model")
include(":feat:findings:fe:app:api")
include(":feat:findings:fe:app:impl")
include(":feat:findings:fe:driving:api")
include(":feat:findings:fe:driving:impl")
include(":feat:findings:fe:ports")
include(":feat:findings:fe:driven:impl")
include(":feat:findings:fe:driven:test")
include(":feat:findings:contract")
include(":feat:findings:be:driving:impl")
include(":feat:findings:be:driven:impl")
include(":feat:findings:be:driven:test")
include(":feat:findings:be:app:api")
include(":feat:findings:be:app:impl")
include(":feat:findings:be:ports")
include(":feat:findings:be:app:model")
include(":feat:structures:business:model")
include(":feat:structures:app:model")
include(":feat:structures:be:app:api")
include(":feat:structures:be:app:impl")
include(":feat:structures:be:driven:impl")
include(":feat:structures:be:driven:test")
include(":feat:structures:be:ports")
include(":feat:structures:be:app:model")
include(":feat:structures:fe:driving:api")
include(":feat:structures:fe:driving:impl")
include(":feat:structures:fe:app:api")
include(":feat:structures:fe:app:impl")
include(":feat:structures:fe:ports")
include(":feat:structures:fe:driven:impl")
include(":feat:structures:fe:driven:test")
include(":feat:sync:model")
include(":feat:sync:be:api")
include(":feat:sync:be:impl")
include(":feat:sync:be:model")
include(":feat:sync:fe:ports")
include(":feat:sync:fe:app:api")
include(":feat:sync:fe:app:impl")
include(":feat:sync:fe:driven:impl")
include(":feat:sync:fe:driven:test")
include(":feat:sync:fe:model")
include(":lib:database:fe")
include(":lib:database:fe:test")
include(":feat:clients:business:model")
include(":feat:clients:business:rules")
include(":feat:clients:app:model")
include(":feat:clients:be:app:model")
include(":feat:clients:be:app:api")
include(":feat:clients:be:app:impl")
include(":feat:clients:be:ports")
include(":feat:clients:be:driven:impl")
include(":feat:clients:be:driven:test")
include(":feat:clients:contract")
include(":feat:clients:be:driving:impl")
include(":feat:clients:fe:app:api")
include(":feat:clients:fe:app:impl")
include(":feat:clients:fe:ports")
include(":feat:clients:fe:driven:impl")
include(":feat:clients:fe:driven:test")
include(":feat:clients:fe:driving:api")
include(":feat:clients:fe:driving:impl")
include(":feat:inspections:business:model")
include(":feat:inspections:app:model")
include(":feat:inspections:fe:app:api")
include(":feat:inspections:fe:app:impl")
include(":feat:inspections:fe:ports")
include(":feat:inspections:fe:driven:impl")
include(":feat:inspections:fe:driven:test")
include(":feat:inspections:fe:driving:api")
include(":feat:inspections:fe:driving:impl")
include(":feat:inspections:be:app:api")
include(":feat:inspections:be:app:impl")
include(":feat:inspections:be:ports")
include(":feat:inspections:be:app:model")
include(":feat:inspections:be:driven:impl")
include(":feat:inspections:be:driven:test")
include(":feat:inspections:contract")
include(":feat:inspections:be:driving:impl")
include(":lib:storage:be:api")
include(":lib:storage:be:impl")
include(":lib:storage:be:test")
include(":lib:storage:contract")
include(":lib:storage:fe:api")
include(":lib:storage:fe:impl")
include(":lib:storage:fe:test")
include(":feat:reports:contract")
include(":feat:reports:business:model")
include(":feat:reports:business:rules")
include(":feat:reports:be:app:model")
include(":feat:reports:be:app:api")
include(":feat:reports:be:app:impl")
include(":feat:reports:be:ports")
include(":feat:reports:be:driven:impl")
include(":feat:reports:be:driven:test")
include(":feat:reports:be:driving:impl")
include(":feat:reports:fe:ports")
include(":feat:reports:fe:app:api")
include(":feat:reports:fe:app:impl")
include(":feat:reports:fe:driven:impl")
include(":feat:reports:fe:driven:test")
include(":feat:authorization:business:model")
include(":feat:authorization:be:driving:api")
include(":feat:authorization:be:driving:impl")
include(":feat:authentication:be:driving:api")
include(":feat:authentication:be:driving:impl")
include(":feat:authentication:be:driving:test")
include(":feat:authentication:app:model")
include(":feat:authentication:fe:app:api")
include(":feat:authentication:fe:app:impl")
include(":feat:authentication:fe:ports")
include(":feat:authentication:fe:driven:impl")
include(":feat:authentication:fe:driven:test")
include(":feat:authentication:fe:driving:api")
include(":feat:authentication:fe:driving:impl")
include(":feat:users:business:model")
include(":feat:users:business:rules")
include(":feat:users:app:model")
include(":feat:users:be:app:model")
include(":feat:users:be:app:api")
include(":feat:users:be:app:impl")
include(":feat:users:be:ports")
include(":feat:users:be:driven:impl")
include(":feat:users:be:driven:test")
include(":feat:users:be:driving:api")
include(":feat:users:contract")
include(":feat:users:be:driving:impl")
include(":feat:users:fe:ports")
include(":feat:users:fe:app:api")
include(":feat:users:fe:app:impl")
include(":feat:users:fe:driving:api")
include(":feat:users:fe:driving:impl")
include(":feat:users:fe:driven:impl")
include(":feat:users:fe:driven:test")
include(":feat:shared:storage:be")
include(":feat:shared:storage:fe")
