#
# Copyright (c) 2026 Timotej Adamec
# SPDX-License-Identifier: MIT
#
# This file is part of the thesis:
# "Multiplatform snagging system with code sharing maximisation"
#
# Czech Technical University in Prague
# Faculty of Information Technology
# Department of Software Engineering
#

snag.mockAuth=false
snag.entraIdTenantId=d4cf541c-fc13-4043-a70f-98c7a9ea1023
snag.entraIdClientId=5f36a648-675f-4aae-9df2-e22093587c6b
