#
# Copyright (c) 2026 Timotej Adamec
# SPDX-License-Identifier: MIT
#
# This file is part of the thesis:
# "Multiplatform snagging system with code sharing maximisation"
#
# Czech Technical University in Prague
# Faculty of Information Technology
# Department of Software Engineering
#

snag.serverTarget=demo
snag.serverLocalhostPort=8081
snag.serverDevUrl=https://snag-server-dev-ioifzecczq-ey.a.run.app
snag.serverDemoUrl=https://snag-server-demo-ioifzecczq-ey.a.run.app
# Platform-specific redirect URIs (MobileRunConfig, JvmRunConfig, WebRunConfig)
snag.entraIdMobileRedirectUri=snag://auth-callback
snag.entraIdJvmRedirectUri=http://localhost:8080/auth-callback
snag.entraIdWebRedirectPath=/web-auth-callback
