#!/usr/bin/env python3
# Copyright (c) 2026 Timotej Adamec
# SPDX-License-Identifier: MIT
#
# Thesis: "Multiplatform snagging system with code sharing maximisation"
# Czech Technical University in Prague -- Faculty of Information Technology
#
# Renders CSV artefacts from analysis/data/ as LaTeX fragments consumed by \input{}
# from text/appendix.tex. Sibling to analysis/figures.py: figures renders .pdf/.png,
# tables renders .tex. Both are deterministic, committed, and regenerated from a
# clean clone by re-running the script from the repo root.
#
# Phase 3 scope: measurement_log_wearos.tex (§4.4 appendix entry). The four other
# appendix placeholders listed in text/appendix.tex (sharing_report, loc_per_feature,
# repair_log_inspections, repair_log_projectphoto) get their own renderer functions
# added during Phase 5 -- the register_renderers() dispatch below is the extension
# point. Each renderer is independent; running `python analysis/tables.py` with no
# arguments regenerates every registered target.
#
# Output path convention: analysis/data-for-thesis/<name>.tex. Thesis repo's
# appendix.tex pulls these via \input{analysis/data-for-thesis/<name>.tex} after the
# file is copied into the thesis repo by the author at writeup time (there is no
# automated bridge between the two repos).
#
# Usage:
#   python analysis/tables.py                 # regenerate all registered tables
#   python analysis/tables.py measurement_log_wearos   # regenerate one table

from __future__ import annotations

import csv
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Callable

ANALYSIS_DIR = Path(__file__).resolve().parent
DATA_DIR = ANALYSIS_DIR / "data"
OUTPUT_DIR = ANALYSIS_DIR / "data-for-thesis"


# ---------------------------------------------------------------------------
# LaTeX escaping
# ---------------------------------------------------------------------------

_LATEX_ESCAPES = {
    "\\": r"\textbackslash{}",
    "&": r"\&",
    "%": r"\%",
    "$": r"\$",
    "#": r"\#",
    "_": r"\_",
    "{": r"\{",
    "}": r"\}",
    "~": r"\textasciitilde{}",
    "^": r"\textasciicircum{}",
    "<": r"\textless{}",
    ">": r"\textgreater{}",
}


def latex_escape(s: str) -> str:
    if s is None:
        return ""
    out = []
    for ch in s:
        out.append(_LATEX_ESCAPES.get(ch, ch))
    return "".join(out)


def code(s: str) -> str:
    """Wrap a short identifier in \\code{} (colorbox-based, non-breaking)."""
    return r"\code{" + latex_escape(s) + "}"


def path_texttt(s: str) -> str:
    """Render a (potentially long) file path as wrappable \\texttt{} with
    \\allowbreak at each / and -> separator. Keeps monospace but lets LaTeX
    break long paths inside p{} columns so the measurement log fits the page."""
    escaped = latex_escape(s)
    # Insert a break opportunity after each forward slash and after the git
    # rename arrow " -> " (now escaped as " -\textgreater{} "). This keeps
    # the visible text unchanged but lets LaTeX break long paths inside
    # narrow p{} columns instead of overflowing.
    broken = escaped.replace("/", r"/\allowbreak{}")
    broken = broken.replace(r" -\textgreater{} ", r" -\textgreater{}\allowbreak{} ")
    return r"\texttt{" + broken + "}"


# ---------------------------------------------------------------------------
# Renderer registry
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class Renderer:
    name: str
    render: Callable[[], str]
    inputs: tuple[Path, ...]

    def output_path(self) -> Path:
        return OUTPUT_DIR / f"{self.name}.tex"


def run(renderer: Renderer) -> None:
    for p in renderer.inputs:
        if not p.is_file():
            raise SystemExit(f"Missing input {p} for {renderer.name}")
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    body = renderer.render()
    out = renderer.output_path()
    header = (
        "% Auto-generated by analysis/tables.py from "
        + ", ".join(str(p.relative_to(ANALYSIS_DIR.parent)) for p in renderer.inputs)
        + ".\n% Do not edit by hand -- rerun `python analysis/tables.py "
        + renderer.name
        + "` to regenerate.\n"
    )
    out.write_text(header + body, encoding="utf-8")
    print(f"wrote {out.relative_to(ANALYSIS_DIR.parent)}", file=sys.stderr)


# ---------------------------------------------------------------------------
# Renderer: measurement_log_wearos
# ---------------------------------------------------------------------------
#
# Input: analysis/data/ripple_wearos-project-list_files.csv (105 rows, one per
# changed file on experiment/wearos-feasibility-spike vs. base 7fb6e2b27).
# Columns consumed: file, bucket, recurring, loc_churn, reason.
# Output: a longtable with columns file / bucket / recurring / LOC / reason,
# grouped by top-level tree (feat/, koinModulesAggregate/, wearApp/, ...) so the
# appendix reader can trace §4.4 prose claims back to individual rows.

_WEAROS_FILES_CSV = DATA_DIR / "ripple_wearos-project-list_files.csv"


def _tree_for(path: str) -> str:
    if " -> " in path:
        path = path.split(" -> ", 1)[1]
    roots = (
        "core/",
        "lib/",
        "feat/",
        "app/",
        "business/",
        "composeApp/",
        "wearApp/",
        "androidApp/",
        "build-logic/",
        "koinModulesAggregate/",
        "testInfra/",
        "server/",
        "gradle/",
    )
    for r in roots:
        if path.startswith(r):
            return r
    if path == "settings.gradle.kts" or path.startswith("settings.gradle"):
        return "settings.gradle.kts"
    return "other"


_TREE_ORDER = (
    "feat/",
    "koinModulesAggregate/",
    "wearApp/",
    "build-logic/",
    "composeApp/",
    "testInfra/",
    "gradle/",
    "settings.gradle.kts",
)


def _render_measurement_log_wearos() -> str:
    rows: list[dict[str, str]] = []
    with _WEAROS_FILES_CSV.open(encoding="utf-8") as f:
        rows = list(csv.DictReader(f))

    lines: list[str] = []
    lines.append(r"\begingroup")
    lines.append(r"\footnotesize")
    lines.append(r"\setlength{\tabcolsep}{4pt}")
    lines.append(
        r"\begin{longtable}{@{}p{0.38\linewidth}p{0.08\linewidth}p{0.05\linewidth}"
        r"p{0.04\linewidth}p{0.38\linewidth}@{}}"
    )
    lines.append(
        r"\caption{Měřicí log experimentu Wear~OS -- "
        r"jeden řádek na každý soubor, který se změnil mezi základem \code{7fb6e2b27} "
        r"a~\code{experiment/wearos-feasibility-spike}. "
        r"Sloupce: cesta souboru, kategorie dopadu (L/V/Vd), příznak opakujícího se zásahu, "
        r"rozsah úprav (LOC) a~klasifikační zdůvodnění.}\label{tab:appendix-measurement-log-wearos}\\"
    )
    lines.append(r"\toprule")
    lines.append(
        r"\textbf{Soubor} & \textbf{Kategorie} & \textbf{Opak.} & \textbf{LOC} & "
        r"\textbf{Zdůvodnění} \\"
    )
    lines.append(r"\midrule")
    lines.append(r"\endfirsthead")
    lines.append(r"\toprule")
    lines.append(
        r"\textbf{Soubor} & \textbf{Kategorie} & \textbf{Opak.} & \textbf{LOC} & "
        r"\textbf{Zdůvodnění} \\"
    )
    lines.append(r"\midrule")
    lines.append(r"\endhead")
    lines.append(r"\bottomrule")
    lines.append(r"\endfoot")

    # Group by tree in canonical order; unknown trees appended alphabetically.
    by_tree: dict[str, list[dict[str, str]]] = {}
    for r in rows:
        by_tree.setdefault(_tree_for(r["file"]), []).append(r)
    seen: set[str] = set()
    ordered: list[str] = []
    for t in _TREE_ORDER:
        if t in by_tree:
            ordered.append(t)
            seen.add(t)
    for t in sorted(by_tree.keys()):
        if t not in seen:
            ordered.append(t)

    _BUCKET_LABEL = {"local": "L", "intrinsic": "V", "collateral": "Vd"}

    for tree in ordered:
        group = sorted(by_tree[tree], key=lambda r: r["file"])
        tree_files = len(group)
        tree_loc = sum(int(r.get("loc_churn", "0") or 0) for r in group)
        lines.append(
            r"\multicolumn{5}{@{}l@{}}{\textbf{"
            + code(tree)
            + r"}"
            + f" -- {tree_files} souborů, {tree_loc} LOC"
            + r"} \\"
        )
        for r in group:
            bucket = _BUCKET_LABEL.get(r["bucket"], r["bucket"])
            recurring = (
                r"\checkmark" if r.get("recurring", "False") == "True" else ""
            )
            loc = r.get("loc_churn", "0") or "0"
            reason = r.get("reason", "") or ""
            lines.append(
                path_texttt(r["file"])
                + " & "
                + bucket
                + " & "
                + recurring
                + " & "
                + loc
                + " & "
                + latex_escape(reason)
                + r" \\"
            )
        lines.append(r"\addlinespace")

    lines.append(r"\end{longtable}")
    lines.append(r"\endgroup")
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Renderer dispatch
# ---------------------------------------------------------------------------


def register_renderers() -> dict[str, Renderer]:
    # Phase 3 scope: measurement_log_wearos.
    # Phase 5 scope (appendix placeholders still on % TODO in text/appendix.tex):
    #   - sharing_report           (analysis/data/sharing_report_with_loc.csv)
    #   - loc_per_feature          (analysis/data/loc_per_source_set.csv + derived)
    #   - repair_log_inspections   (analysis/data/ripple_inspections-reverse-removal_*.csv)
    #   - repair_log_projectphoto  (analysis/data/ripple_projectphoto-forward_*.csv)
    # Each gets its own _render_<name>() and a Renderer(...) line below when Phase 5 lands.
    registry = {
        "measurement_log_wearos": Renderer(
            name="measurement_log_wearos",
            render=_render_measurement_log_wearos,
            inputs=(_WEAROS_FILES_CSV,),
        ),
    }
    return registry


def main(argv: list[str]) -> int:
    registry = register_renderers()
    if len(argv) > 1:
        selected = argv[1:]
        unknown = [s for s in selected if s not in registry]
        if unknown:
            print(f"Unknown renderer(s): {', '.join(unknown)}", file=sys.stderr)
            print(f"Available: {', '.join(sorted(registry))}", file=sys.stderr)
            return 2
        targets = [registry[s] for s in selected]
    else:
        targets = list(registry.values())
    for r in targets:
        run(r)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
